# Generated by Django 3.0.7 on 2020-06-28 19:27

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': "Page d'accueil"},
        ),
        migrations.AddField(
            model_name='homepage',
            name='biography_heading',
            field=models.CharField(default='', max_length=128, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='biography_subheading',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Sous-titre'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='biography_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='homepage',
            name='experience_heading',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='experience_subheading',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Sous-titre'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='experiences',
            field=wagtail.core.fields.StreamField([('experience', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=128)), ('date', wagtail.core.blocks.CharBlock(max_length=128)), ('subheading', wagtail.core.blocks.CharBlock(max_length=128, required=False)), ('text', wagtail.core.blocks.TextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_heading',
            field=models.CharField(default='', max_length=128, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_lead',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Slogan'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_slide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Slide'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_subheading',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Sous-titre'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services',
            field=wagtail.core.fields.StreamField([('service', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=128)), ('text', wagtail.core.blocks.TextBlock()), ('icon', wagtail.core.blocks.CharBlock(max_length=128))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='skill_heading',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='skill_subheading',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Sous-titre'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='skills',
            field=wagtail.core.fields.StreamField([('skill', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=128)), ('subheading', wagtail.core.blocks.CharBlock(help_text='Sous-titre dans la vue grille', max_length=128, required=False)), ('intro', wagtail.core.blocks.CharBlock(help_text='Sous-titre dans la vue modal (grand écran)', max_length=255, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.TextBlock(required=False))]))], blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='homepage',
            table='portfolio_homepage',
        ),
        migrations.CreateModel(
            name='PortfolioSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_keywords', models.CharField(blank=True, default='', max_length=256, verbose_name='Mots clés SEO')),
                ('seo_description', models.CharField(blank=True, default='', max_length=512, verbose_name='Description SEO')),
                ('google_analytics_id', models.CharField(blank=True, default='', max_length=128, verbose_name='Google Analytics ID')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'db_table': 'portfolio_settings',
            },
        ),
    ]
